name: dnabert2
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argcomplete=1.12.3
  - argh=0.26.2
  - asciitree=0.3.3
  - bedtools=2.30.0
  - blas=1.0
  - blosc=1.21.0
  - bokeh=2.4.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - cffi=1.14.6
  - charset-normalizer=2.1.0
  - cloudpickle=2.0.0
  - cooler=0.8.11
  - cryptography=37.0.2
  - cudatoolkit=11.6.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask=2022.7.0
  - dask-core=2022.7.0
  - dbus=1.13.18
  - deeptools=3.5.1
  - deeptoolsintervals=0.1.9
  - dill=0.3.4
  - distributed=2022.7.0
  - expat=2.4.4
  - fastp=0.22.0
  - fastqc=0.11.9
  - ffmpeg=4.3
  - fftw=3.3.9
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.7.1
  - future=0.18.2
  - gdbm=1.18
  - gffutils=0.11.0
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gtfparse=1.2.1
  - h5py=3.7.0
  - hdf5=1.10.6
  - heapdict=1.0.1
  - hicmatrix=16
  - htslib=1.13
  - icu=58.2
  - idna=3.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.84.0
  - libdeflate=1.7
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - locket=1.0.0
  - lz4=3.1.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=2.1.1
  - matplotlib-base=3.3.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - msgpack-python=1.0.3
  - multiprocess=0.70.12.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.6
  - numexpr=2.8.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - olefile=0.46
  - openh264=2.1.1
  - openjdk=11.0.13
  - openjpeg=2.4.0
  - openssl=1.1.1s
  - packaging=21.3
  - pairix=0.3.7
  - partd=1.2.0
  - pcre=8.45
  - perl=5.34.0
  - pillow=8.2.0
  - pip=22.1.2
  - plotly=5.9.0
  - psutil=5.9.0
  - py2bit=0.3.0
  - pybigwig=0.3.18
  - pycparser=2.21
  - pyfaidx=0.7.0
  - pyfasta=0.5.2
  - pygenometracks=3.6
  - pyopenssl=22.0.0
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.28.1
  - seaborn=0.11.2
  - setuptools=61.2.0
  - simplejson=3.17.6
  - sip=4.19.13
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.38.5
  - tblib=1.7.0
  - tenacity=8.0.1
  - tk=8.6.12
  - toolz=0.11.2
  - torchaudio=0.12.0
  - torchvision=0.13.0
  - tornado=6.1
  - tqdm=4.64.0
  - typing_extensions=4.3.0
  - urllib3=1.26.10
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zict=2.1.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.1.0
    - anndata==0.8.0
    - attrs==22.1.0
    - biopython==1.79
    - boto3==1.24.28
    - botocore==1.27.28
    - bx==0.3.0
    - bx-python==0.9.0
    - cachetools==5.2.0
    - click==8.1.3
    - coloredlogs==15.0.1
    - colormath==3.0.0
    - commonmark==0.9.1
    - contourpy==1.0.5
    - crossmap==0.6.4
    - cython==0.29.32
    - deprecated==1.2.13
    - filelock==3.7.1
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - humanfriendly==10.0
    - importlib-metadata==4.12.0
    - transformers==2.4.1
    # - transformers
    - jeepney==0.8.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.1.0
    - jsonschema==4.16.0
    - keyring==23.4.1
    - keyrings-alt==3.1
    - llvmlite==0.39.1
    - lzstring==1.0.4
    - markdown==3.3.7
    - matplotlib==3.6.1
    - modin==0.15.3
    - multiqc==1.13
    - natsort==8.2.0
    - networkx==2.8.7
    - nose==1.3.7
    - numba==0.56.3
    - oauthlib==3.2.0
    - pandas==1.4.4
    - patsy==0.5.2
    - protobuf==3.19.4
    - pyahocorasick==1.4.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybedtools==0.9.0
    - pygments==2.13.0
    - pynndescent==0.5.7
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pysam==0.19.1
    - pytz-deprecation-shim==0.1.0.post0
    - regex==2022.7.9
    - requests-oauthlib==1.3.1
    - rich==12.6.0
    - rich-click==1.5.2
    - rpy2==3.5.3
    - rsa==4.8
    - rseqc==4.0.1
    - s3transfer==0.6.0
    - sacremoses==0.0.53
    - scanpy==1.9.1
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - secretstorage==3.3.3
    - sentencepiece==0.1.94
    - seqeval==1.2.2
    - session-info==1.0.0
    - sklearn==0.0
    - spectra==0.0.11
    - statsmodels==0.13.2
    - stdlib-list==0.8.0
    - synapseclient==2.7.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - threadpoolctl==3.1.0
    # - tokenizers==0.5.0
    - tokenizers==0.0.11
    - tzdata==2022.1
    - tzlocal==4.2
    - umap-learn==0.5.3
    - uuid==1.30
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - zipp==3.8.1
