install.packages('gplots', repos='https://cran.rstudio.com', dependencies = TRUE)  
install.packages('countdata', repos='https://cran.rstudio.com')  
install.packages('Rtsne', repos='https://cran.rstudio.com') 
install.packages('GGally', repos='https://cran.rstudio.com') 
install.packages('ggrepel', repos='https://cran.rstudio.com') 
install.packages('httr', repos='https://cran.rstudio.com') 
install.packages('png', repos='https://cran.rstudio.com') 
install.packages('umap', repos='https://cran.rstudio.com')
install.packages('calibrate', repos='https://cran.rstudio.com')

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("Rhtslib")
BiocManager::install("DESeq2", dependencies = TRUE)
BiocManager::install("EnhancedVolcano")